name: user_repository
description: The repo that handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  rxdart: ^0.28.0

  plant_repository:
    path: ../plant_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
